### ISSUE TITLE
unary operator "-" for Vector3 missing for Python API?

### ISSUE THREAD

**Issue by smoe** [BALL-Project/ball#556]
Hello,

I have an atom's position assigned to v (yes, I am about to have some moving peptide chains, soon :o) ) . Here it is:
<pre>
In [33]: v
Out[3]: <BALLCore.Vector3 at 0x7f07cb8d6938>
In [34]: print(v)
(4.715000 3.664000 8.503000)
</pre>

I also found a way to negate all its values

<pre>
In [32]: print(Vector3(0,0,0)-v)
(-4.715000 -3.664000 -8.503000)
</pre>

but wished it would be more intuitive like

<pre>
In [31]: print(-v)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-5b34ae81aae1> in <module>()
----> 1 print(-v)

TypeError: bad operand type for unary -: 'Vector3'
</pre>

I had seen it defined in 
https://github.com/BALL-Project/ball/blob/3bbc2107984f63f988a3e60dfdc2a71531a2a809/include/BALL/MATHS/vector3.h#L297
but not in the sip file
https://github.com/BALL-Project/ball/blob/3bbc2107984f63f988a3e60dfdc2a71531a2a809/source/PYTHON/EXTENSIONS/BALL/vector3.sip|vector3.sip

As I know now I could have invoked "negate()" on v, but I had created v only for this bug report and initially worked with the someAtom.getPosition(), directly. The atom position I do not intend to negate, though.

Shall I provide a patch? Or is there something awkward that I just fail to anticipate?

**Comment by dstoeckel** [comment]
I cannot remember that there was something awkward with that. Python should support overloading the unary minus. I suppose we just missed the function while wrapping or it might be that SIP didn't really support this. It would be great, if you could provide a patch for this.

In general, there may be quite some functions missing from the Python interface, because I doubt anybody of the developers is using the bindings extensively...

**Comment by dstoeckel** [comment]
Pull request has been merged.
