### ISSUE TITLE
Require Qt 5.4 as minimum version

### ISSUE THREAD

**Issue by dstoeckel** [BALL-Project/ball#585]
For Wayland to work we need at least Qt 5.4 which allows us to port from QGLWidget to QOpenGLWidget. See:

https://bugreports.qt.io/browse/QTBUG-29024
https://blog.qt.io/blog/2014/09/10/qt-weekly-19-qopenglwidget/

Unfortunately, Qt 5.4 is not supported on the Ubuntu 14.04 LTS release which we should support for at least a while. Are there any other distros we care about that have a Qt version less than 5.4?

**Comment by philthiel** [comment]
We decided to care about Centos7 (maybe also 6). However, none of them provides Qt5 at all.
So we have to rely on ball_contrib in both cases. Wouldn't this also be the solution for Ubuntu 14?

**Comment by tkemmer** [comment]
Also, we need at least Qt 5.5 for the current QtWebEngine port. Otherwise, we cannot use `QWebEnginePage::acceptNavigationRequest` (required by PresentaBALL) and `QWebEngineDownloadItem` (required by BALLaxy; although this could be replaced by a nasty WebEngine-NetworkAccessManager hybrid).

**Comment by anhi** [comment]
I would prefer not to add the hack, but rather make BALLaxy compilation conditional on the Qt version.

Von: Thomas Kemmer <notifications@github.com<mailto:notifications@github.com>>
Antworten an: BALL-Project/ball <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 29. April 2016 um 08:23
An: BALL-Project/ball <ball@noreply.github.com<mailto:ball@noreply.github.com>>
Betreff: Re: [BALL-Project/ball] Require Qt 5.4 as minimum version (#585)


Also, we need at least Qt 5.5 for the current QtWebEngine port. Otherwise, we cannot use QWebEnginePage::acceptNavigationRequest (required by PresentaBALL) and QWebEngineDownloadItem (required by BALLaxy; although this could be replaced by a nasty WebEngine-NetworkAccessManager hybrid).

**Comment by dstoeckel** [comment]
> We decided to care about Centos7 (maybe also 6). However, none of them provides Qt5 at all.
> So we have to rely on ball_contrib in both cases. Wouldn't this also be the solution for Ubuntu 14?

It probably would be, but I really, really dislike the monster compile times for Qt. Anyway, I am fine with raising requirements as we will most likely update to 16.04 in the near future.

> I would prefer not to add the hack, but rather make BALLaxy compilation conditional on the Qt version.

Agreed! I still have recurring nightmares from the Qt4 SimpleDownloader hack ...

**Comment by tkemmer** [comment]
Okay, but the conditional compilation should not be limited to BALLaxy but to WebEngine support in general since PresentaBALL and potentially all future WebEngine widgets are affected as well. This is due to `QWebEnginePage::acceptNavigationRequest` in `VIEW::HTMLPage` which delegates command links to the Python interpreter and prevents freezes caused by click events when BALLView is busy.

**Comment by tkemmer** [comment]
I just noticed that the installation manuals on our website already state Qt 5.4 as minimum version (http://www.ball-project.org/installation/, all platforms). So, can the current master branch still be built with lower Qt versions anyway?

**Comment by dstoeckel** [comment]
On 04/29/2016 01:19 PM, Thomas Kemmer wrote:
> I just noticed that the installation manuals on our website
> already state Qt 5.4 as minimum version 
> (http://www.ball-project.org/installation/, all platforms). So, can
> the current master branch still be built with lower Qt versions
> anyway?
> 

For me it is building on Qt 5.2 on Ubuntu 14.04.

**Comment by tkemmer** [comment]
`USE_QTWEBENGINE=ON` now enforces Qt 5.5+ (71288e51f8bd2147166ce2490e4cbbf60a63e1d1).

**Comment by gerddie** [comment]
Coming from Debian, were  [qt4-webkit](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784451) will be dropped soon, and hence the move to QT5 will be required, I'd like to chime in that Qt5.5 for 14.04 is available from at least one [PPA](https://launchpad.net/~alex-p/+archive/ubuntu/qt-5.5.1).

**Comment by a17r** [comment]
I don't see how some Distro LTS release that is most likely not going to update from ball-1.4.2 should hold you back on master branch requirements. The bugs present in pre-Qt-5.6 make me feel sorry for everyone still stuck with it...

**Comment by philthiel** [comment]
Thomas and I decided to raise minimum required version to 5.6 (534ac6005bfe3002c70d30d3e4f7ac27a9dfa913).
