### ISSUE TITLE
BALLView preferences dialog does not show up.

### ISSUE THREAD

**Issue by philthiel** [BALL-Project/ball#586]
The attempt to open BALLView's preferences dialog actually opens the force field options dialog of the currently selected force field.

Systems:
- OS X 10.10 / 10.11
- Xcode 7
- ball_contrib

**Comment by tkemmer** [comment]
Does this error also occur when using the `Ctrl+Z` keyboard shortcut?

Just to make sure, you didn't accidentally confuse `Molecular Mechanics -> Options` with `Edit -> Preferences`? I had this problem myself once or twice-ish. Maybe it's time to rename the option to something more specific in any case.

**Comment by philthiel** [comment]
- On osx cmd+z works. 
- Based on your tip, I recognized that 'Molecular Mechanics -> Options' menu entry is entirely missing.

**Comment by tkemmer** [comment]
Unintentionally fixed with 4033b9a2444828343b9ae1bfdc44fe82f7529cc6. I could reproduce the problem on my MacBook (OSX 10.11) and apparently, the whole "let's move the settings option to the app menu and bind it to cmd+,"-thingy works name-based and removed both the `Edit -> Preferences` and `Molecular Mechanics -> Options` entries and just used the latter as actual Preferences option.
